
export enum CART_ITEM_CONSTAINTS {
    GET_LIST_PRODUCTS_REQUEST = 'GET_LIST_PRODUCTS_REQUEST',
    GET_LIST_PRODUCTS_SUCCESS = 'GET_LIST_PRODUCTS_SUCCESS',
    GET_LIST_PRODUCTS_REJECT = 'GET_LIST_PRODUCTS_REJECT'
}